#!/usr/bin/env python3
"""Generate BPR camera effect prototypes for Upgrade Kits."""

from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
if str(PYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_ROOT))

from Common.bpr_common import get_weapon_families

CONTENT_DIR = PYTHON_ROOT.parent
OUTPUT_FILE = (
    CONTENT_DIR
    / "GameLite"
    / "ModGameData"
    / "Testmod"
    / "EffectPrototypes"
    / "BPR_CamEffectPrototypes.cfg"
)


def render_effect(family: str) -> str:
    effect_sid = f"BPR_{family}_UpgradeKit_ShakeEffect"
    shake_sid = f"BPR_{family}_UpgradeKit_Shake"
    return "\n".join([
        f"{effect_sid} : struct.begin {{refurl=@BaseGame/EffectPrototypes.cfg;refkey=[0]}}",
        f"   SID = {effect_sid}",
        "   Type = EEffectType::CameraShake",
        "   Positive = EBeneficial::Negative",
        "   CameraShakeEffectSubtype = ECameraShakeEffectSubtype::AddEffect",
        f"   CameraShakePrototypeSID = {shake_sid}",
        "struct.end",
    ])


def main() -> None:
    families = get_weapon_families()
    sections = [render_effect(family) for family in families]

    header = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Python/Config/weapon_progression.json",
        "// Generated by: generate_camera_effects.py",
        "// -----------------------------------------------------------------------------",
    ]

    output = "\n".join(header + ["", "\n\n".join(sections)]) + "\n"
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(output, encoding="utf-8")

    print("Camera Effect Prototype CFG Generator")
    print("--------------------------------------")
    print(f"Weapon families:   {len(families)}")
    print(f"Generated effects: {len(sections)}")
    print(f"Written to:\n{OUTPUT_FILE}")


if __name__ == "__main__":
    main()
