#!/usr/bin/env python3
"""Generate CameraShakePrototypes_patch_BPR.cfg from cameraShakes.json."""

from __future__ import annotations

import json
from pathlib import Path


# =============================================================================
# Paths
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent
CONTENT_DIR = SCRIPT_DIR.parents[2]

CONFIG_FILE = SCRIPT_DIR / "cameraShakes.json"

OUTPUT_FILE = (
    CONTENT_DIR
    / "GameLite"
    / "GameData"
    / "CameraShakePrototypes"
    / "CameraShakePrototypes_patch_BPR.cfg"
)


# =============================================================================
# Config
# =============================================================================

BLUEPRINT_ROOT = "/Testmod/Shakes"

TEMPLATE_SID = "BPR_UpgradeKitTemplate_Shake"


# =============================================================================
# Helpers
# =============================================================================

def load_config(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def validate_config(config: dict) -> None:
    families = config.get("weapon_families")

    if not isinstance(families, list) or not families:
        raise ValueError(
            "'weapon_families' must contain at least one weapon family."
        )

    if any(
        not isinstance(family, str) or not family.strip()
        for family in families
    ):
        raise ValueError(
            "Every weapon family must be a non-empty string."
        )

    duplicates = {
        family
        for family in families
        if families.count(family) > 1
    }

    if duplicates:
        raise ValueError(
            "Duplicate weapon family/families: "
            + ", ".join(sorted(duplicates))
        )


# =============================================================================
# CFG generation
# =============================================================================

def render_template() -> str:
    lines = [
        (
            f"{TEMPLATE_SID} : struct.begin "
            "{refurl=@BaseGame/CameraShakePrototypes.cfg;refkey=[0]}"
        ),
        f"   SID = {TEMPLATE_SID}",
        "   Type = ECameraShakeType::Constant",
        "   Priority = 0",
        "   CameraShakePath = Blueprint''",
        "   GroupSID = Concussion",
        "   Scale = 1.0",
        "struct.end",
    ]

    return "\n".join(lines)


def render_family_shake(family: str) -> str:
    shake_sid = f"BPR_{family}_UpgradeKit_Shake"
    blueprint_name = f"BPR_{family}_UpgradeKit"

    blueprint_path = (
        f"Blueprint'{BLUEPRINT_ROOT}/"
        f"{blueprint_name}.{blueprint_name}'"
    )

    lines = [
        (
            f"{shake_sid} : struct.begin "
            f"{{refkey={TEMPLATE_SID}}}"
        ),
        f"   SID = {shake_sid}",
        f"   CameraShakePath = {blueprint_path}",
        "struct.end",
    ]

    return "\n".join(lines)


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    print("Camera Shake Prototype CFG Generator")
    print("------------------------------------")
    print(f"Config: {CONFIG_FILE}")
    print(f"Output: {OUTPUT_FILE}")
    print()

    if not CONFIG_FILE.exists():
        raise FileNotFoundError(
            f"Config file not found:\n{CONFIG_FILE}"
        )

    config = load_config(CONFIG_FILE)
    validate_config(config)

    families = config["weapon_families"]

    sections = [render_template()]
    sections.extend(
        render_family_shake(family)
        for family in families
    )

    header = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Python/CFGGenerators/CameraShakeGenerator/cameraShakes.json",
        "// Generated by: generate_cameraShakes.py",
        "// -----------------------------------------------------------------------------",
    ]

    output = "\n".join(
        header + ["", "\n\n".join(sections)]
    ) + "\n"

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    OUTPUT_FILE.write_text(
        output,
        encoding="utf-8",
    )

    print("Generation successful.")
    print()
    print(f"Weapon families: {len(families)}")
    print(f"Generated shakes: {len(families)}")
    print(f"Written to:\n{OUTPUT_FILE}")


if __name__ == "__main__":
    main()