#!/usr/bin/env python3
"""Generate BPR camera shake prototypes for Upgrade Kits."""

from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
if str(PYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_ROOT))

from Common.bpr_common import get_weapon_families

CONTENT_DIR = PYTHON_ROOT.parent
OUTPUT_FILE = (
    CONTENT_DIR
    / "GameLite"
    / "ModGameData"
    / "Testmod"
    / "CameraShakePrototypes"
    / "BPR_CameraShakePrototypes.cfg"
)

BLUEPRINT_ROOT = "/Testmod/Shakes"
TEMPLATE_SID = "BPR_UpgradeKitTemplate_Shake"


def render_template() -> str:
    return "\n".join([
        f"{TEMPLATE_SID} : struct.begin {{refurl=@BaseGame/CameraShakePrototypes.cfg;refkey=[0]}}",
        f"   SID = {TEMPLATE_SID}",
        "   Type = ECameraShakeType::Constant",
        "   Priority = 0",
        "   CameraShakePath = Blueprint''",
        "   GroupSID = Concussion",
        "   Scale = 1.0",
        "struct.end",
    ])


def render_family_shake(family: str) -> str:
    shake_sid = f"BPR_{family}_UpgradeKit_Shake"
    blueprint_name = f"BPR_{family}_UpgradeKit"
    blueprint_path = f"Blueprint'{BLUEPRINT_ROOT}/{blueprint_name}.{blueprint_name}'"
    return "\n".join([
        f"{shake_sid} : struct.begin {{refkey={TEMPLATE_SID}}}",
        f"   SID = {shake_sid}",
        f"   CameraShakePath = {blueprint_path}",
        "struct.end",
    ])


def main() -> None:
    families = get_weapon_families()
    sections = [render_template()]
    sections.extend(render_family_shake(family) for family in families)

    header = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Python/Config/weapon_progression.json",
        "// Generated by: generate_camera_shakes.py",
        "// -----------------------------------------------------------------------------",
    ]

    output = "\n".join(header + ["", "\n\n".join(sections)]) + "\n"
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(output, encoding="utf-8")

    print("Camera Shake Prototype CFG Generator")
    print("------------------------------------")
    print(f"Weapon families:  {len(families)}")
    print(f"Generated shakes: {len(families)}")
    print(f"Written to:\n{OUTPUT_FILE}")


if __name__ == "__main__":
    main()
