#!/usr/bin/env python3
"""Generate BPR stash loot pools and vanilla stash patches."""

from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
if str(PYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_ROOT))

from Common.bpr_common import (
    RANK_ORDER,
    VANILLA_RANKS,
    cumulative_families,
    load_json,
    load_weapon_progression,
    logical_rank_for_vanilla,
    tier_blueprint_sid,
    upgrade_kit_sid,
)

CONTENT_DIR = PYTHON_ROOT.parent
STASH_CONFIG_FILE = SCRIPT_DIR / "stash_loot.json"

BASEGAME_ITEM_GENERATOR_DIR = CONTENT_DIR / "GameLite" / "GameData" / "ItemGeneratorPrototypes"
MOD_ITEM_GENERATOR_DIR = CONTENT_DIR / "GameLite" / "ModGameData" / "Testmod" / "ItemGeneratorPrototypes"
DYNAMIC_ITEM_GENERATOR_DIR = BASEGAME_ITEM_GENERATOR_DIR / "DynamicItemGenerator"
GENERATORS_OUTPUT = MOD_ITEM_GENERATOR_DIR / "BPR_Stashes_ItemGeneratorPrototypes.cfg"
PATCH_OUTPUT = DYNAMIC_ITEM_GENERATOR_DIR / "GamePassItemGeneratorPrototypes_patch_BPR.cfg"
TIER_KEYS = (("tier_1", 1), ("tier_2", 2), ("tier_3", 3))


def validate_stash_config(config: dict) -> None:
    chances = config.get("drop_chances")
    generators = config.get("stash_generators")
    if not isinstance(chances, dict):
        raise ValueError("Missing or invalid 'drop_chances'.")
    for key, _ in TIER_KEYS + (("upgrade_kit", 0),):
        if key not in chances:
            raise ValueError(f"Missing drop chance: {key}")
        chance = float(chances[key])
        if not 0.0 <= chance <= 1.0:
            raise ValueError(f"{key} must be between 0 and 1, got {chance}")
    if not isinstance(generators, list) or not generators:
        raise ValueError("'stash_generators' must contain at least one SID.")
    if len(generators) != len(set(generators)):
        raise ValueError("Duplicate stash generator SID found.")


def render_header(output_path: Path) -> list[str]:
    relative_path = output_path.relative_to(CONTENT_DIR)
    return [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Sources:",
        "//   Python/Config/weapon_progression.json",
        "//   Python/CFGGenerators/Distribution/stash_loot.json",
        "// Generated by: generate_stash_blueprints.py",
        f"// Output: Content/{relative_path.as_posix()}",
        "// -----------------------------------------------------------------------------",
        "",
    ]


def render_item_pool(sid: str, item_sids: list[str]) -> list[str]:
    lines = [
        f"{sid} : struct.begin {{refurl=@BaseGame/ItemGeneratorPrototypes.cfg;refkey=[0]}}",
        f"   SID = {sid}",
        "   ItemGenerator : struct.begin",
        "      [*] : struct.begin",
        "         Category = EItemGenerationCategory::Junk",
        "         bAllowSameCategoryGeneration = true",
        "         PossibleItems : struct.begin",
    ]
    for item_sid in item_sids:
        lines.extend([
            "            [*] : struct.begin",
            f"               ItemPrototypeSID = {item_sid}",
            "               Weight = 1",
            "               MinCount = 1",
            "               MaxCount = 1",
            "            struct.end",
        ])
    lines.extend([
        "         struct.end",
        "      struct.end",
        "   struct.end",
        "struct.end",
        "",
    ])
    return lines


def render_roll_entry(pool_sid: str, chance: float) -> list[str]:
    return [
        "      [*] : struct.begin",
        "         Category = EItemGenerationCategory::SubItemGenerator",
        "         bAllowSameCategoryGeneration = true",
        "         PossibleItems : struct.begin",
        "            [*] : struct.begin",
        f"               ItemGeneratorPrototypeSID = {pool_sid}",
        f"               Chance = {chance:g}",
        "               MinCount = 1",
        "               MaxCount = 1",
        "            struct.end",
        "         struct.end",
        "      struct.end",
    ]


def render_rank_roll_generator(rank: str, stash_config: dict) -> list[str]:
    sid = f"BPR_StashRolls_{rank}"
    lines = [
        f"{sid} : struct.begin {{refurl=@BaseGame/ItemGeneratorPrototypes.cfg;refkey=[0]}}",
        f"   SID = {sid}",
        "   ItemGenerator : struct.begin",
    ]
    for chance_key, tier in TIER_KEYS:
        lines.extend(render_roll_entry(
            f"BPR_StashBlueprint_{rank}_Tier_{tier}",
            float(stash_config["drop_chances"][chance_key]),
        ))
    lines.extend(render_roll_entry(
        f"BPR_StashUpgradeKit_{rank}",
        float(stash_config["drop_chances"]["upgrade_kit"]),
    ))
    lines.extend(["   struct.end", "struct.end", ""])
    return lines


def generate_generators(weapon_config: dict, stash_config: dict) -> str:
    lines = render_header(GENERATORS_OUTPUT)
    for rank in RANK_ORDER:
        families = cumulative_families(weapon_config, rank)
        lines.extend([
            "// -----------------------------------------------------------------------------",
            f"// {rank} - {len(families)} cumulative weapon families",
            "// -----------------------------------------------------------------------------",
            "",
        ])
        for _, tier in TIER_KEYS:
            lines.extend(render_item_pool(
                f"BPR_StashBlueprint_{rank}_Tier_{tier}",
                [tier_blueprint_sid(weapon_config, family, tier) for family in families],
            ))
        lines.extend(render_item_pool(
            f"BPR_StashUpgradeKit_{rank}",
            [upgrade_kit_sid(weapon_config, family) for family in families],
        ))
        lines.extend(render_rank_roll_generator(rank, stash_config))
    return "\n".join(lines).rstrip() + "\n"


def generate_patch(weapon_config: dict, stash_config: dict) -> str:
    lines = render_header(PATCH_OUTPUT)
    lines.extend([
        "// [*] is intentional: BPR appends entries without relying on fixed array indices.",
        "",
    ])
    for stash_sid in stash_config["stash_generators"]:
        lines.extend([
            f"{stash_sid} : struct.begin {{bpatch}}",
            "   ItemGenerator : struct.begin {bpatch}",
        ])
        for vanilla_rank in VANILLA_RANKS:
            logical_rank = logical_rank_for_vanilla(weapon_config, vanilla_rank)
            lines.extend([
                "      [*] : struct.begin",
                "         Category = EItemGenerationCategory::SubItemGenerator",
                "         bAllowSameCategoryGeneration = true",
                f"         PlayerRank = ERank::{vanilla_rank}",
                "         PossibleItems : struct.begin",
                "            [*] : struct.begin",
                f"               ItemGeneratorPrototypeSID = BPR_StashRolls_{logical_rank}",
                "               Chance = 1",
                "               MinCount = 1",
                "               MaxCount = 1",
                "            struct.end",
                "         struct.end",
                "      struct.end",
            ])
        lines.extend(["   struct.end", "struct.end", ""])
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    weapon_config = load_weapon_progression()
    stash_config = load_json(STASH_CONFIG_FILE)
    validate_stash_config(stash_config)

    MOD_ITEM_GENERATOR_DIR.mkdir(parents=True, exist_ok=True)
    DYNAMIC_ITEM_GENERATOR_DIR.mkdir(parents=True, exist_ok=True)
    GENERATORS_OUTPUT.write_text(generate_generators(weapon_config, stash_config), encoding="utf-8")
    PATCH_OUTPUT.write_text(generate_patch(weapon_config, stash_config), encoding="utf-8")

    print("BPR Stash Distribution Generator")
    print("--------------------------------")
    print(f"Generated: {GENERATORS_OUTPUT}")
    print(f"Generated: {PATCH_OUTPUT}")
    print("Drop chances:")
    for key in ("tier_1", "tier_2", "tier_3", "upgrade_kit"):
        print(f"  {key}: {stash_config['drop_chances'][key]:.2%}")


if __name__ == "__main__":
    main()
