#!/usr/bin/env python3
"""Generate vanilla upgrade patches that require BPR blueprint tiers."""

from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[2]
if str(PYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_ROOT))

from Common.bpr_common import get_weapon_families, load_json, load_weapon_progression, tier_blueprint_sid

CONTENT_DIR = PYTHON_ROOT.parent
CONFIG_PATH = SCRIPT_DIR / "upgrade_blueprint_tiers.json"
OUTPUT_PATH = CONTENT_DIR / "GameLite" / "GameData" / "UpgradePrototypes" / "UpgradePrototypes_patch_BPR.cfg"


def validate_config(config: dict, weapon_config: dict) -> None:
    upgrades = config.get("upgrades")
    if not isinstance(upgrades, list) or not upgrades:
        raise ValueError("Missing or invalid 'upgrades' list.")

    known_families = set(get_weapon_families(weapon_config))
    seen_upgrade_sids: set[str] = set()

    for index, item in enumerate(upgrades, start=1):
        upgrade_sid = item.get("upgrade_sid")
        family = item.get("family")
        blueprint_tier = item.get("blueprint_tier")

        if not upgrade_sid:
            raise ValueError(f"Entry #{index} has no upgrade_sid.")
        if upgrade_sid in seen_upgrade_sids:
            raise ValueError(f"Duplicate upgrade SID: {upgrade_sid}")
        if family not in known_families:
            raise ValueError(f"Upgrade '{upgrade_sid}' references unknown family '{family}'.")
        if blueprint_tier not in (1, 2, 3):
            raise ValueError(
                f"Upgrade '{upgrade_sid}' has invalid blueprint_tier: {blueprint_tier}"
            )
        seen_upgrade_sids.add(upgrade_sid)


def render_upgrade(item: dict, weapon_config: dict) -> str:
    upgrade_sid = item["upgrade_sid"]
    blueprint_sid = tier_blueprint_sid(
        weapon_config,
        item["family"],
        item["blueprint_tier"],
    )
    return "\n".join([
        f"{upgrade_sid} : struct.begin {{bpatch}}",
        "   RequiredItemPrototypeSIDs : struct.begin",
        f"      [0] = {blueprint_sid}",
        "   struct.end",
        "struct.end",
    ])


def main() -> None:
    config = load_json(CONFIG_PATH)
    weapon_config = load_weapon_progression()
    validate_config(config, weapon_config)

    upgrades = config["upgrades"]
    tier_counts = {1: 0, 2: 0, 3: 0}
    family_counts: dict[str, int] = {}

    lines = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Sources:",
        "//   Python/Config/weapon_progression.json",
        "//   Python/CFGGenerators/Upgrades/upgrade_blueprint_tiers.json",
        "// Generated by: generate_upgrade_blueprint_tiers.py",
        "// -----------------------------------------------------------------------------",
        "",
    ]

    current_family = None
    for item in upgrades:
        family = item["family"]
        if family != current_family:
            if current_family is not None:
                lines.append("")
            lines.extend([
                "// ------------------------------------------------------------",
                f"// {family}",
                "// ------------------------------------------------------------",
            ])
            current_family = family

        lines.append(render_upgrade(item, weapon_config))
        lines.append("")
        tier = item["blueprint_tier"]
        tier_counts[tier] += 1
        family_counts[family] = family_counts.get(family, 0) + 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    print("Upgrade Blueprint Tier CFG Generator")
    print("------------------------------------")
    print(f"Upgrade entries: {len(upgrades)}")
    print(f"Families:        {len(family_counts)}")
    print(f"Tier 1:          {tier_counts[1]}")
    print(f"Tier 2:          {tier_counts[2]}")
    print(f"Tier 3:          {tier_counts[3]}")
    print(f"Written to:\n{OUTPUT_PATH}")


if __name__ == "__main__":
    main()
