#!/usr/bin/env python3
"""Generate Upgrade Kit consumable ItemPrototypes."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[2]
if str(PYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_ROOT))

from Common.bpr_common import get_weapon_families, load_json, load_weapon_progression, upgrade_kit_sid

CONTENT_DIR = PYTHON_ROOT.parent
CONFIG_FILE = SCRIPT_DIR / "upgrade_kits.json"
OUTPUT_FILE = (
    CONTENT_DIR
    / "GameLite"
    / "ModGameData"
    / "Testmod"
    / "ItemPrototypes"
    / "ConsumablePrototypes"
    / "BPR_UpgradeKit_ConsumablePrototypes.cfg"
)

REQUIRED_SETTINGS = (
    "mod_root",
    "icon_path",
    "mesh_prototype_sid",
    "item_grid_width",
    "item_grid_height",
    "cost",
    "weight",
    "sort_group",
    "consumable_type",
    "ui_use_sound",
)


def fmt_number(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def validate_config(config: dict) -> None:
    settings = config.get("settings")
    if not isinstance(settings, dict):
        raise ValueError("Missing or invalid 'settings' object.")
    for key in REQUIRED_SETTINGS:
        if key not in settings:
            raise ValueError(f"Missing required setting: '{key}'")


def render_upgrade_kit(family: str, settings: dict, weapon_config: dict) -> str:
    item_sid = upgrade_kit_sid(weapon_config, family)
    effect_sid = f"BPR_{family}_UpgradeKit_ShakeEffect"
    icon_name = f"T_UpgradeKit_{family}"
    icon_reference = (
        f"Texture2D'/{settings['mod_root']}/{settings['icon_path']}/"
        f"{icon_name}.{icon_name}'"
    )

    return "\n".join([
        f"{item_sid} : struct.begin {{refurl=@BaseGame/ItemPrototypes/ConsumablePrototypes.cfg;refkey=Bread}}",
        f"    SID = {item_sid}",
        f"    Icon = {icon_reference}",
        f"    MeshPrototypeSID = {settings['mesh_prototype_sid']}",
        f"    ItemGridWidth = {fmt_number(settings['item_grid_width'])}",
        f"    ItemGridHeight = {fmt_number(settings['item_grid_height'])}",
        f"    Cost = {fmt_number(settings['cost'])}",
        f"    Weight = {fmt_number(settings['weight'])}",
        f"    SortGroup = {settings['sort_group']}",
        f"    ConsumableType = {settings['consumable_type']}",
        f"    UIUseSound = {settings['ui_use_sound']}",
        "    AnimBlueprint = AnimBlueprint''",
        "",
        "    EffectPrototypeSIDs : struct.begin",
        f"        [0] = {effect_sid}",
        "        [1] = None",
        "        [2] = None",
        "        [3] = None",
        "        [4] = None",
        "    struct.end",
        "",
        "    ShouldShowEffects : struct.begin",
        "        [0] = false",
        "        [1] = false",
        "        [2] = false",
        "        [3] = false",
        "        [4] = false",
        "    struct.end",
        "",
        "    EffectsDisplayTypes : struct.begin",
        "        [0] = EEffectDisplayType::Value",
        "        [1] = EEffectDisplayType::Value",
        "        [2] = EEffectDisplayType::Value",
        "        [3] = EEffectDisplayType::Value",
        "        [4] = EEffectDisplayType::Value",
        "    struct.end",
        "struct.end",
    ])


def main() -> None:
    config = load_json(CONFIG_FILE)
    validate_config(config)
    weapon_config = load_weapon_progression()
    families = get_weapon_families(weapon_config)
    settings = config["settings"]

    header = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Sources:",
        "//   Python/Config/weapon_progression.json",
        "//   Python/CFGGenerators/UpgradeKits/upgrade_kits.json",
        "// Generated by: generate_upgrade_kit_items.py",
        "// -----------------------------------------------------------------------------",
        "",
    ]
    blocks = [render_upgrade_kit(family, settings, weapon_config) for family in families]
    output = "\n".join(header) + "\n\n".join(blocks) + "\n"

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(output, encoding="utf-8")

    print("Upgrade Kit ItemPrototype CFG Generator")
    print("---------------------------------------")
    print(f"Upgrade kits generated: {len(families)}")
    print(f"Written to:\n{OUTPUT_FILE}")


if __name__ == "__main__":
    main()
